services:
  postgresql:
    image: postgres:14.18
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: pets
    ports:
      - "5432:5432"
    volumes:
      - postgresql_pets_data:/var/lib/postgresql/data
    networks:
      - pet-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_pets_data:/var/lib/rabbitmq
    networks:
      - pet-network

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/config/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
      - ./config/loki:/etc/loki/config:ro
    networks:
      - pet-network

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: -config.file=/etc/promtail/config/promtail-config.yml
    ports:
      - "9080:9080"
    volumes:
      - ./config/promtail:/etc/promtail/config:ro
      - ./logs:/var/pets-logs:ro
    networks:
      - pet-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - pet-network
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge

volumes:
  postgresql_pets_data:
  rabbitmq_pets_data:
  loki_data:
  grafana_data:
