spring:
  application:
    name: pets
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pets}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /

security:
  jwt:
    secret-key: ${JWT_SECRET:ce5e82685b90de63d1548054beab3b5e691d257c07799db1d073002d34b6ac09}
    expiration-time: ${JWT_EXPIRATION:3600000}

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:domain-events}
    routing-prefix: ${RABBITMQ_ROUTING_PREFIX:events}
    queues:
      user-created-log: ${RABBITMQ_QUEUE_USER_CREATED_LOG:user-created-log.q}
